name: Rename SEP Folders to NOV
on: workflow_dispatch

jobs:
  rename:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Rename Folders
        run: |
          # Define the base path
          BASE="ssc/mts"

          # Rename 12 Sep Shift 3
          if [ -d "$BASE/" ]; then
            mv "$BASE/MTS-2025-4-FEB-SHIFT-3" "$BASE/MTS-2025-04-FEB-SHIFT-3"
          fi


      - name: Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Renamed 12, 13, 14 SEP folders to NOV"
          git push
